### ISSUE TITLE
Big Mac Theory Data Visualization Proposal

### ISSUE THREAD

**Issue by zoejab** [zoejab/BigMac#1]
@jasonseminara 

The Big Mac Theory was created by The Economist to illustrate the concept of Purchasing Power Parity (PPP). The definition of PPP, according to The Economist, is "the notion that in the long run exchange rates should move towards the rate that would equalise the prices of an identical basket of goods and services (in this case, a burger) in any two countries." Essentially, this shows us (with a baseline of the USD) how undervalued or overvalued a Big Mac is. 

Implementation: I will be creating a world map in D3 to represent the data of prices of Big Macs worldwide. You will be able to hover over countries to see information about the prices of the burgers and it will generate historical graphs and comparison graphs to other countries. 

Technologies used: Currency Exchange API, D3, GeoJson, Economist dataset of historical prices of Big Macs in 50+ different countries. Node/Express/Angular/Mongo/Javascript.

**Comment by jasonseminara** [comment]
Love it so far!
My fear is that the data set may be overwhelming. What can you do to make sure the information is presented in a usable and pleasant manner?  

Here are some ideas that would make it wonderful:
* Log in/out; remember selected country in session?
* email notifications for [price drops, location spikes, etc]
* See historical data
* choose a different product to track (future release?)

**Comment by jasonseminara** [comment]
What do you think about the above? Please respond.

**Comment by zoejab** [comment]
Sounds good except I dont think sessions are necessary for this type of application but I have a zoomed in map ready and I'm working on my database stuff at the moment. If I can find some more data on a good around the world I could expand but I'd have to find a relevant dataset first.
